version: '3.8'

services:
  backend:
    image: ghcr.io/braydenidzenga/zettanote-backend:latest
    container_name: zettanote-backend
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DB=${DB}
      - JWT_SECRET=${JWT_SECRET}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:4000/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - zettanote-network

  frontend:
    image: ghcr.io/braydenidzenga/zettanote-frontend:latest
    container_name: zettanote-frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost/']
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - zettanote-network

  admin-portal:
    image: ghcr.io/braydenidzenga/zettanote-admin:latest
    container_name: zettanote-admin
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
      - PORT=3001
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3001/']
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - zettanote-network

networks:
  zettanote-network:
    driver: bridge
